# PATCH this Dancer option into your metrics config

[ScreenPlayerOptions]

LineNames="...,Dancer,..." # add Dancer to your LineNames
LineDancer="lua,CustomOptionRow('Dancer')" # add this line to anywhere within ScreenPlayerOptions
